# jekyll configuration
# --------------------
permalink: /:year/:month/:day/:title/
highlighter: rouge
markdown: kramdown
exclude: ['readme.md', 'Gemfile.lock', 'Gemfile', 'run.sh', 'CNAME']
plugins: [jekyll-paginate]
paginate: 3
paginate_path: "pages/:num/"

# site configuration
# ------------------
url: https://www.stefanglase.de
title: stefanglase.de
description: 'Hier bloggt Stefan Glase über Softwareentwicklung, Mountainbiking und allerlei andere Dinge.'
keywords: 'Mountainbike, Enduro, Java, Softwareentwicklung, Groovy, Grails, Maven, Spring, BitvUnit'
author: Stefan Glase
email: stefan.glase@googlemail.com

# google analytics
# ----------------
google_analytics_code: UA-22676933-1

# github ribbon
# -------------
github_username: codescape

# comments with disqus
# --------------------
disqus_username: stefanglase
